# Site settings
title: Gaussian Process Summer Schools
author:
  name: GP Summer School
  email: 
description: > # this means to ignore newlines until "baseurl:"
  Gaussian process summer schools teach the theory and practice of
  Gaussian processes. This site gives details of schools past and present.
baseurl: "" # the subpath of your site, e.g. /blog/
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
logo: "gpss_logo.svg"
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool
analytics:
  google:
    tracking_id: UA-62991754-1
# Build settings
markdown: kramdown
